logstash:
  image: logstash:2.3.3
  volumes:
    - ./logstash/logstash.conf:/tmp/logstash.conf
  ports:
    - 5141:5141/udp
  net: host
  restart: always
  command: logstash -f /tmp/logstash.conf

kibana:
  image: kibana:4.5.1
  ports:
    - 5601:5601
  environment:
    - ELASTICSEARCH_URL=http://localhost:9200
  net: host
  restart: always
